/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/common/Button.vue')['default']
    GeneralInput: typeof import('./components/common/GeneralInput.vue')['default']
    SvgIcon: typeof import('./components/common/SvgIcon.vue')['default']
  }
}
